log_settings = "config/dealer_logs_prod.yml"
env = "Prod"
bitcoin_amount_submit = 0.025
bitcoin_amount_min = 0.0001
bitcoin_amount_max = 1.0
apikey = ""
proxy_port = 4101

server_host = "api.sideswap.io"
server_port = 443
server_use_tls = true
notificationurl = ""
status_port = 4002

bitfinexkey = "<YOUR_BITFINEX_KEY>"
bitfinexsecret = "<YOUR_BITFINEX_SECRET>"

bitfinex_bookname_usdt = "tBTCUST"
bitfinex_bookname_eurx = "tBTCEUR"

bitfinex_withdraw_address = "<YOUR_BITFINEX_WITHDRAW_ADDR>"
bitfinex_fund_address = "<YOUR_BITFINEX_FUND_ADDR>"

bitfinex_currency_btc = "BTC"
bitfinex_currency_lbtc = "LBT"
bitfinex_currency_usdt = "UST"
bitfinex_currency_eur = "EUR"

storage_path = "config/storage_prod.txt"
balancing_enabled = true

[rpc]
host = "<YOUR_ELEMENTS_HOST>"
port = 12345
login = "<YOUR_ELEMENTS_LOGIN>"
password = "<YOUR_ELEMENTS_PASSWORD>"

[module]
host = "localhost"
port = 4101

[notifications]
# optional slack notifications url
url = ""
