[package]
name = "sideswap_common"
version = "0.1.0"
edition = "2018"

[dependencies]
sideswap_api = { version = "*", path = "../sideswap_api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "*"
anyhow = "*"
dirs = "3.0.1"
reqwest = { version = "*", features = ["blocking", "json"] }
log = "*"
async-tungstenite = { version = "*", features = ["tokio-native-tls"] }
futures = "*"
futures-util = "*"
tokio = "*"
tungstenite = { version = "*" }
derive_more = "*"
