server_host = "api.sideswap.io"
server_port = 443
server_use_tls = true
api_key = "<YOUR_DEALER_API_KEY>"
log_settings = "config/dealer_example_logs.yml"
bitcoin_mainnet = false
max_trade_size = 0.1

[rpc]
host = "localhost"
port = 38501
login = ""
password = 1231

[zmq]
host = "localhost"
port = 14356
